name: pml_units

channels:
  - pytorch
  - pytorch-test
  - nvidia
  - conda-forge

dependencies:
  - python>=3.10

  - blas=*.*=mkl

  - cuda-cudart
  - cuda-cudart-dev
  - cuda-libraries
  - cuda-libraries-dev
  - cuda-nvcc
  - cuda-runtime
  - cudatoolkit
  - cudnn
  - libcusparse
  - libcusparse-dev

  - git>=2.34.1
  - jpeg
  - libpng>=1.6.37

  - conda>=22.9
  - importlib_metadata>=4.11.3
  - pep517>=0.12
  - pip-tools>=6.6
  - pip>=22.2
  - setuptools>=65.5
  - wheel>=0.37.1

  - dataclasses>=0.8
  - regex>=2022.7
  - rich>=12.5
  - tqdm>=4.64.1

  - joblib>=1.1
  - multiprocess>=0.70.12.2
  - threadpoolctl>=2.2

  - cython>=0.29.32
  - matplotlib>=3.5.3
  - numpy>=1.23.3
  - pandas>=1.4.4
  - scikit-learn>=1.1.3
  - scipy>=1.8.1
  - seaborn>=0.12
  - statsmodels>=0.13.2

  - ipyparallel
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab

  - pytorch-cuda=11.8
  - pytorch-mutex=*.*=cuda
  - pytorch>=2
  - torchvision>=0.15

  - gpytorch>=1.9
  - linear_operator>=0.1.1
  - pyro-api>=0.1.2
  - pyro-ppl>=1.8.2

  - libjpeg-turbo>=2.1.4
  - pillow>=9.2

  - pip:
      - tyxe>=0.0.2
